### ISSUE TITLE
Problème du nombre de caractères du détail d'une actualité quand on place une image

### ISSUE THREAD

**Issue by cdaviau** [GIP-RECIA/esup-publisher#14]
Quand on place une image dans le détail d'une actualité, on devrait pouvoir ne pas être obligé de saisir 15 caractères mini.

**Comment by jgribonvald** [comment]
Pour moi un problème se pose, mettre une image uniquement ne convient pas à ce type de saisi !
De plus mettre une image dans l'éditeur ne permet pas de faire du RWD, d'où le typage du contenu.
