### ISSUE TITLE
Publication document: les types autorisés ne sont pas pris en compte

### ISSUE THREAD

**Issue by jgribonvald** [GIP-RECIA/esup-publisher#145]
Quand on clique sur le bouton pour charger un document (publication dont le contenu est de type document), dans l'imput est indiqué la liste des MIME type de fichiers autorisés. Cela n'est pas correctement pris en charge par Firefox (pas testé avec un autre navigateur) et ne permet que de récupérer par défaut des Images ou vidéos (pas de fichier autre type PDF par exemple). 
Je soupçonne que cela soit lié au type de baslise HTML utilisée, à savoir un bouton à la place d'une input de type file, mais cela est aussi lié à la directive/module Angular car il y a un système très utile en plus permettant de gérer la taille maximale du fichier à télécharger.
Pour remédier à cela l'utilisateur est obligé de modifier le filtre du parcourir par "Tous les types de fichiers", tout le monde ne comprend pas cela.

**Comment by jgribonvald** [comment]
Cette issue est à vérifier plus en détail car elle semble être résolu avec la migration frontend

**Comment by slafon51** [comment]
@jgribonvald Bonjour Julien, on a le même comportement entre la version AngularJs et la version VueJS.

Le problème semble provenir du navigateur Firefox qui gére pas dans l'attribut "accept" la valeur "application/*" (cf. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers).
Il faudrait donc à la place de "application/*" mettre la liste des extensions de fichier autorisées de type application (.pdf, .docx, ...).

Peux-tu me dire quelle est la liste des fichiers de type application/* pouvant être uploadé pour les contenus de type document et média ?

Merci d'avance.

**Comment by jgribonvald** [comment]
@slafon51: il y a un fichier https://github.com/GIP-RECIA/esup-publisher/blob/migration-frontend/src/main/resources/MimeTypes.txt dans le projet, ce fichier (conf via la property  `app.upload.filePathOfAuthorizedMimeTypes`) est chargé et dispo via l'API via #216. Par contre je pense qu'il faut filtrer selon le besoin, mais pour les images normalement c'est déjà filtré.
Est-ce que ça convient ?

**Comment by slafon51** [comment]
@jgribonvald Merci Julien. Je viens de faire une Pull Request afin d'utiliser ces mimetypes sur le formulaires des contenus de type Document et Média.
