### ISSUE TITLE
Faire apparaître différemment les contextes visibles en page d'accueil et les autres

### ISSUE THREAD

**Issue by cdaviau** [GIP-RECIA/esup-publisher#15]
Pour éviter les confusions, il serait souhaitable de différentier visuellement les contextes qui seront vus en page d'accueil (actualité, flash-infos) des autres (documents) dans la partie "Gérer" de l'application et éventuellement sur la première page de "Piblier". Ce pourrait être un pictogramme ou une couleur différente...

**Comment by jgribonvald** [comment]
Pour moi les contextes devraient être nommés où avoir une description indiquant le nom du service où cela est publié.
