### ISSUE TITLE
Paramètrage Image cropper

### ISSUE THREAD

**Issue by jgribonvald** [GIP-RECIA/esup-publisher#160]
L'image cropper a une configuration spécifique pour les flash-info, cette configuration n'a pas été ré-appliquée.

l'ancien code se basait sur ces éléments:

```
$scope.defaultCropperConf = {
            size:[{w:240, h:240}],
            quality: 0.9,
            format: 'image/jpeg',
            type: 'rectangle',
            changeOnFly: false,
            allowCropResizeOnCorners: false
        };
$scope.cropperConf = angular.copy($scope.defaultCropperConf);

        $scope.initCropper = function(){

            switch ($scope.content.type) {
                case 'NEWS':
                    $scope.cropperConf.size = [{w:240, h:240}];
                    $scope.cropperConf.type = "square";
                    break;
                case 'FLASH':
                    $scope.cropperConf.size = [{w:800, h:240}];
                    $scope.cropperConf.quality = 0.8;
                    $scope.cropperConf.type = "rectangle";
                    $scope.cropperConf.ratio = 3.3;
                    break;
                default :
                    $scope.cropperConf = angular.copy($scope.defaultCropperConf);break;
            }
        };
```

**Comment by slafon51** [comment]
@jgribonvald Bonjour Julien, actuellement l'image cropper est configuré pour que :
- l'image obtenue pour les actualités soit un carré de 240px sur 240px
- l'image obtenue pour les flash-infos soit un rectangle de 800px sur 240px

![cropper](https://user-images.githubusercontent.com/95467649/158978954-95734f4f-0370-456c-89e3-35351735dcd9.png)

Après différents tests, cette configuration semble bien prise en compte.
Pourrais-tu me détailler le comportement qui te semble incorrect ?

Merci d'avance.

**Comment by jgribonvald** [comment]
Bon j'ai eu le pb ce matin, mais j'avais bidouillé un peu sur le formulaire de saisie avant d'aller sur le cropper, je ne reproduis plus le problème rencontré donc c'est étrange.

je vais mettre un autre tag sur l'issue pour la mettre en attente de reproduction. Si je ne reproduis pas je la fermerais.

**Comment by jgribonvald** [comment]
Bon j'ai reproduis le pb, c'est quand on fait précédent pour changer de contexte de publication (sélection d'un autre établissement).
