### ISSUE TITLE
Intégration iframe non reportée

### ISSUE THREAD

**Issue by jgribonvald** [GIP-RECIA/esup-publisher#161]
Le script permettant l'intégration iframe dans le portail n'a pas été reporté.
cf codde d'origine:
```
<script ng-if="ISINIFRAME" src="bower_components/iframe-resizer/postMessage-resize-iframe-in-parent.js"></script>
```
Sauf erreur la lib est celle-ci: https://github.com/davidjbradshaw/iframe-resizer

**Comment by slafon51** [comment]
@jgribonvald Bonjour Julien,
j'ai l'impression que la librairie utilisée n'est pas iframe-resizer (https://github.com/davidjbradshaw/iframe-resizer) mais celle-ci (non présent sur npm) : https://github.com/EsupPortail/iframe-autoheight-using-postMessage
Est-ce que j'utilise iframe-resizer (mais je pense qu'il faudrait que les sites affichant esup-publisher dans une iframe soient mis à jour également pour utiliser cette même librairie) ou est-ce que je réutilise la même libraire que la version AngularJS ?

Merci d'avance.

**Comment by jgribonvald** [comment]
@slafon51 où as tu trouvé la lib utilisée ? j'avoue que je n'ai retrouvé que le chargement de la lib citée...

Par contre dans le portail tu peux trouver l'autre qui est disponible sur notre frontal via l'URL `/commun/postMessage-resize-iframe-in-parent.js` le script est dispo sur tous nos domaines.

**Comment by jgribonvald** [comment]
@slafon51 bon finalement je cromprend ce que j'ai fait, j'ai créé mon propre dossier bower où j'ai importé le js "maison"

je ne sais pas si tu peux l'importer comme ça ou via un v-if avec le chemin relatif au domaine ?
