### ISSUE TITLE
Trait de curseur

### ISSUE THREAD

**Issue by jgribonvald** [GIP-RECIA/esup-publisher#164]
J'ai un comportement étrange lors du survol avec la souris (sous firefox - pas testé autrement), j'ai cliqué mais en glissant (ça na pas valider le submit et c'est resté sur la page).
![Sélection_267](https://user-images.githubusercontent.com/1597283/159056311-74f92fbc-9b8e-4cc8-8ae6-2cfa4ea8885f.png)
En fait c'est le curseur comme d'une zone de saisie de texte ! ça clignotte comme le curseur...

**Comment by slafon51** [comment]
@jgribonvald Bonjour Julien, je n'arrive pas à reproduire ce comportement (tests effectués sur les dernières versions de Firefox (98.0.1), Edge (99.0.1150.46) et Chrome (99.0.4844.82)).
Pourrais-tu me dire quelle version de Firefox tu utilises et si tu as des extensions d'installer qui pourrait engendrer ce comportement ?

Merci d'avance.

**Comment by jgribonvald** [comment]
@slafon51 je pense qu'il faut oublier cette issue, je reproduis uniquement avec Firefox lors d'un déplcement avec tabulation... Ce doit être un indicateur de position.
