### ISSUE TITLE
Couleur du text-editor valide

### ISSUE THREAD

**Issue by jgribonvald** [GIP-RECIA/esup-publisher#165]
Les input valides sont en vert avec que l'éditeur de texte est en bleu. Est-ce la couleur par défaut du composant ? ça ne me choque pas, c'est juste que ça n'est pas uniforme au reste.
![Sélection_268](https://user-images.githubusercontent.com/1597283/159057225-d421833e-fb54-42dc-9f9c-f72a8519a5a4.png)

**Comment by slafon51** [comment]
@jgribonvald Bonjour Julien, il s'agit bien de la couleur par défaut du composant. Je viens de créer une pull request pour surcharger la couleur afin qu'elle soit identique aux autres champs (selon si le champ est valide ou invalide).
