### ISSUE TITLE
Problème sur les limites de dates de publication

### ISSUE THREAD

**Issue by jgribonvald** [GIP-RECIA/esup-publisher#166]
Le système vérifiant les plages de date de début et de fin de publication est bugué.
Si je change la date de début, puis la date de fin de publication, puis que je reviens modifier la date de début à par exemple un mois après, puis que je retourne pour changer la date de fin le limiteur de date de fin n'est plus appliqué et on peut saisir une date en dehors de la période autorisée. 
![Sélection_270](https://user-images.githubusercontent.com/1597283/159229952-cf4b32ed-912c-4f88-926e-e8d8e8bf99f3.png)

De même la date de début ne se réinitialise plus au bout d'un moment et la date minimum de saise peut passer à un mois de la date du jour qui est autorisée.
![Sélection_269](https://user-images.githubusercontent.com/1597283/159229657-f5a15e88-0933-40ba-b492-6dd24dfdc83b.png)
Par contre on ne peut pas faire suite dans la publication quand on est dans ce cas de figure.

**Comment by slafon51** [comment]
@jgribonvald Julien, j'ai fait une pull request qui corrige le calcul des limites des dates de publications.

Pour le cas de la date de début dont le minimum n'est pas la date du jour, je reproduis ce cas lorsque je modifie la date de début et qu'ensuite je fais retour (pour modifier la structure par exemple) et je reviens sur le formulaire. La borne minimum de la date de début est alors égale à la date de début saisie au préalable. C'est un comportement que je reproduis sur la version AngularJS également.
C'est lié à la fonction updateMinDate (https://github.com/GIP-RECIA/esup-publisher/blob/a84c053bad48788c1ca66fc1f1895ed5094d834c/src/main/webapp/scripts/app/manager/publish/content/content.controller.js#L53) qui met à jour la borne minimum avec la date de début de l'item en cours d'édition lors de l'affichage du formulaire.

Faut-il faire évoluer ce comportement ?

Merci d'avance.

**Comment by jgribonvald** [comment]
Bonjour @slafon51,

Nous reproduisons le problème où la sélection d'une date de début n'est pas possible quand on édite une actualité expirée depuis plusieurs mois (je n'avais pas vu le pb avant car je testais sur des expirations récentes.
Le selecteur de date est grisé et donc bloqué, sans doute du fait que la date de fin est elle aussi très antérieure. Par contre on peut saisir manuellement une date (pas forcément pratique, là aussi il y a un petit soucis qui oblige à commencer par l'année).

Merci par avance

**Comment by slafon51** [comment]
@jgribonvald Bonjour Julien, je prend note de ce bug. Cependant, je ne pourrais le traiter qu'à partir de la semaine prochaine.

Cordialement,
Sébastien LAFON.
