### ISSUE TITLE
Missing dependency for packaging

### ISSUE THREAD

**Issue by jgribonvald** [GIP-RECIA/esup-publisher#169]
@slafon51 Lors du lancement de la commande `./mvnw clean package -P prod -Dmaven.test.skip=true -Darguments="-DskipTests -Dmaven.deploy.skip=true"` le packaging ne se fait pas correctement, la dépendance postcss-url est manquante.
Voici les changements que cela apporte lors de l'ajout et install de la dépendance: https://github.com/GIP-RECIA/esup-publisher/commit/0a922f786a6cdda1a9344c9ff3e54f17ee5b4c7b
Pouvez-vous valider cela ? Merci

**Comment by slafon51** [comment]
@jgribonvald Bonjour Julien, l'ajout de la dépendance postcss-url ne semble pas avoir d'impact.
Souhaites-tu que je crée une pull request avec cette ajout ?

Merci d'avance.

**Comment by jgribonvald** [comment]
Merci pour la confirmation, je n'en doutais pas mais je préfairais avoir confirmation. Le commit a été poussé ;)
