### ISSUE TITLE
Classement des documents par ordre alphabétique

### ISSUE THREAD

**Issue by cdaviau** [GIP-RECIA/esup-publisher#20]
Signalement de l'ITS Tours : il semble que la demande de classement des documents par ordre alphabétique ne fonctionne pas.
À vérifier...

**Comment by jgribonvald** [comment]
ça ne touche que l'ITS !

**Comment by jgribonvald** [comment]
À vérifier, mais ne concerne pas publisher

**Comment by jgribonvald** [comment]
Le pb vient d'ici: https://github.com/GIP-RECIA/esup-publisher/blob/migration-frontend/src/main/java/org/esupportail/publisher/web/PublishController.java#L399

l'appel étnt générique il faudrait trouver une solution pour gérer en fonction du displayOrder des catégories avec le nouveau mode qui livre tous les contenus pour un contexte de publication au lieu de catégorie par catégorie (pour éviter les doublons).
Il faudrait peut-être voir pour fournir le mode d'ordonnancement à esup-lecture qui lui décidera, et par défaut on reste tel quel.

**Comment by jgribonvald** [comment]
Géré depuis ça: https://github.com/GIP-RECIA/esup-publisher/commit/aa8aa74e1e62eb62cc37673dc20ae67a95c357e0
