### ISSUE TITLE
Ajout d'un Subject déjà existant dans les permissions non géré

### ISSUE THREAD

**Issue by jgribonvald** [GIP-RECIA/esup-publisher#231]
L'ajout d'un subject déjà défini dans les permissions n'est pas géré comme auparavant 
la copie d'écran pour avant:
![Sélection_285](https://user-images.githubusercontent.com/1597283/162229901-915ed1f5-1157-4cf0-bf2e-982aa02d1eff.png)

Alors que maintenant:
![Sélection_286](https://user-images.githubusercontent.com/1597283/162230134-0b217f4b-deee-4a73-8c4c-fa6b28d7a35f.png)

De plus je note que quand on a déplié l'arborescence auparavant elle se rouvrait au même niveau, alors que maintenant elle est réinitialisée et on doit refaire les requêtes. Il faudrait savoir de quoi ça vient dans un premier temps.

**Comment by slafon51** [comment]
@jgribonvald Bonjour Julien, le comportement différent au niveau de l'arbre dans le subject-search-button vient du fait qu'actuellement l'arbre est détruit à la fermeture de la modale (cf. https://github.com/GIP-RECIA/esup-publisher-webcomponents/blob/9edea737a0a61f8b85be8e9d049ff128ad0635cc/%40gip-recia/subject-search-button/src/subject-search-button.js#L590).
Souhaites-tu que je corrige ce comportement pour être identique à la version AngularJs ?

Merci d'avance.

**Comment by jgribonvald** [comment]
@slafon51 Bonjour, la seule chose qui me gène dans tous cela est de refaire les requêtes à chaque fois qu'on va chercher un nouveau subject après en avoir ajouté un. Donc soit il faut un cache sur la requête à quelques minutes soit il faut détruire quand on change de contexte, mais j'ai peur que cela apporte des effets de bord à faire l'étape "en dehors". Si tu penses que ça n'apportera pas d'effet de bord tu peux, mais il faut vérifier que si on change de contexte avec des droits différents selon le contexte le nouvel arbre est changé.
Merci par avance
