### ISSUE TITLE
Message du validateur

### ISSUE THREAD

**Issue by cdaviau** [GIP-RECIA/esup-publisher#3]
Quand on revient en édition sur un article déjà publié, la date de début de publication est antérieure à la date du jour et donc on ne peut pas passer à l'écran suivant. Le message d'erreur est mis en grisé, ce qui fait qu'on ne le voit pas. Il faudrait donc : 
- soit mettre le message en rouge dès qu'on arrive sur la page d'édition de l'article
- soit ne pas tenir compte de la date de publication quand on revient sur un article déjà publié pour lequel on n'a pas modifié la date de début de publication.

**Comment by jgribonvald** [comment]
Problème avec le bouton de retour uniquement
